name: media-stack

# Reusable Anchors

x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

x-common-env: &common-env
  TZ: ${TZ}
  LOG_LEVEL: ${LOG_LEVEL}

x-linuxserver-env: &linuxserver-env
  PUID: ${PUID}
  PGID: ${PGID}
  UMASK: ${UMASK}

x-healthcheck-timing: &default-healthcheck
  start_period: 30s
  start_interval: 3s
  interval: 30s
  timeout: 5s
  retries: 3

# Services

services:
  # Upstream acquisition support
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    
    volumes:
      - ./prowlarr-config:/config
    
    ports:
      - "9696:9696"
    
    environment:
      <<: [*common-env, *linuxserver-env]
    
    healthcheck:
      test: curl -f http://localhost:9696/ping || exit 1
      <<: *default-healthcheck
    <<: *default-logging

  # Core acquisition
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    
    volumes:
      - ./sonarr-config:/config
      - ${MEDIA_PATH}:${MEDIA_PATH}
    
    ports:
      - "8989:8989"
    
    environment:
      <<: [*common-env, *linuxserver-env]
    
    healthcheck:
      test: curl -f http://localhost:8989/ping || exit 1
      <<: *default-healthcheck
    <<: *default-logging

  sonarr4k:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr4k
    restart: unless-stopped
    
    volumes:
      - ./sonarr4k-config:/config
      - ${MEDIA_PATH}:${MEDIA_PATH}
    
    ports:
      - "8990:8990"
    
    environment:
      <<: [*common-env, *linuxserver-env]
    
    healthcheck:
      test: curl -f http://localhost:8990/ping || exit 1
      <<: *default-healthcheck
    <<: *default-logging

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    
    volumes:
      - ./radarr-config:/config
      - ${MEDIA_PATH}:${MEDIA_PATH}
    
    ports:
      - "7878:7878"
    
    environment:
      <<: [*common-env, *linuxserver-env]
    
    healthcheck:
      test: curl -f http://localhost:7878/ping || exit 1
      <<: *default-healthcheck
    <<: *default-logging

  radarr4k:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr4k
    restart: unless-stopped
    
    volumes:
      - ./radarr4k-config:/config
      - ${MEDIA_PATH}:${MEDIA_PATH}
    
    ports:
      - "7879:7879"
    
    environment:
      <<: [*common-env, *linuxserver-env]
    
    healthcheck:
      test: curl -f http://localhost:7879/ping || exit 1
      <<: *default-healthcheck
    <<: *default-logging

  # Supporting acquisition services

  profilarr:
    image: ghcr.io/dictionarry-hub/profilarr:latest
    container_name: profilarr
    restart: unless-stopped
    
    volumes:
      - ./profilarr-config:/config
    
    ports:
      - "6868:6868"
    
    environment:
      <<: [*common-env, *linuxserver-env]
      ORIGIN: ${PROFILARR_ORIGIN}
    
    healthcheck:
      test: curl -f http://localhost:6868/ || exit 1
      <<: *default-healthcheck
    <<: *default-logging

  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    restart: unless-stopped
    
    volumes:
      - ${MEDIA_PATH}:${MEDIA_PATH}
    
    environment:
      <<: [*common-env, *linuxserver-env]
      TEST_RUN: "False"
      TIMER: 10

      SONARR: >
        - base_url: "http://sonarr:8989"
          api_key: "${SONARR_API_KEY}"
        - base_url: "http://sonarr4k:8990"
          api_key: "${SONARR4K_API_KEY}"
      RADARR: >
        - base_url: "http://radarr:7878"
          api_key: "${RADARR_API_KEY}"
        - base_url: "http://radarr4k:7879"
          api_key: "${RADARR4K_API_KEY}"
      QBITTORRENT: >
        - base_url: "${QBITTORRENT_URL}"
          username: "${QBITTORRENT_USER}"
          password: "${QBITTORRENT_PASS}"
          name: "qBittorrent"

      REMOVE_BAD_FILES: "True"
      REMOVE_FAILED_DOWNLOADS: "True"
      REMOVE_FAILED_IMPORTS: "False"
      REMOVE_METADATA_MISSING: "True"
      REMOVE_MISSING_FILES: "True"
      REMOVE_ORPHANS: "True"
      REMOVE_SLOW: "True"
      REMOVE_STALLED: "True"
      REMOVE_UNMONITORED: "True"
      SEARCH_UNMET_CUTOFF: "True"
      SEARCH_MISSING: "True"
      DETECT_DELETIONS: "True"

    healthcheck:
      test: pgrep -f python || exit 1
      <<: *default-healthcheck
    <<: *default-logging

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    restart: unless-stopped
    init: true
    
    volumes:
      - ./seerr-config:/app/config
    
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    
    ports:
      - "5055:5055"
    
    environment:
      <<: *common-env
      PORT: 5055
    
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      <<: *default-healthcheck
    <<: *default-logging

  # Media consumption
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    
    volumes:
      - ./jellyfin-config:/config
      - ./jellyfin-cache:/cache
      - ${MEDIA_PATH}:${MEDIA_PATH}
    devices:
      - /dev/dri:/dev/dri
    
    user: ${PUID}:${PGID}
    group_add:
      - "44"
      - "992"
    
    ports:
      - "8096:8096/tcp"
      - "7359:7359/udp"
      - "1900:1900/udp"
    
    environment:
      <<: *common-env
      JELLYFIN_PublishedServerUrl: ${JELLYFIN_URL}
    
    healthcheck:
      test: curl -f http://localhost:8096/System/Info/Public || exit 1
      <<: *default-healthcheck
    <<: *default-logging

  tunarr:
    image: chrisbenincasa/tunarr:latest
    container_name: tunarr
    restart: unless-stopped
    profiles:
      - tunarr
    
    volumes:
      - ./tunarr-config:/config/tunarr
    devices:
      - /dev/dri:/dev/dri
    
    group_add:
      - "44"
      - "992"
    
    ports:
      - 8000:8000
    
    environment:
      <<: *common-env
      LOG_LEVEL: ${LOG_LEVEL}

    healthcheck:
      test: curl -f http://localhost:8000/api/version || exit 1
      <<: *default-healthcheck
    <<: *default-logging
